---
# https://fpm.readthedocs.io/en/latest/installing.html

- name: Install Ruby 4 Debian and Ubuntu
  when: ansible_distribution in ['Debian', 'Ubuntu']
  become: yes
  apt:
    name:
      - ruby
      - ruby-dev
      - rubygems
      - build-essential
    state: present
    install_recommends: yes

- name: Install Ruby 4 Fedora\CentOS 8
  when:
    - ansible_os_family == 'RedHat'
    - ansible_pkg_mgr == 'dnf'
  become: yes
  dnf:
    name:
      - ruby-devel
      - gcc
      - make
      - rpm-build
      - libffi-devel

- name: Install Ruby 4 OpenSUSE
  when:
    - ansible_system == 'Linux'
    - ansible_os_family == 'Suse'
    - ansible_pkg_mgr == 'zypper'
  become: yes
  zypper:
    name:
      - ruby
      - ruby-devel
      - gcc
      - make
      - libffi-devel
    state: present

# https://stackoverflow.com/a/48212945/5430535
- name: Dirty fucking hack for CentOS, Fedora and OpenSUSE in docker for escape error "Use --install-dir or --user-install but not both"
  when:
    - ansible_system == 'Linux'
    - ansible_os_family in ['Suse', 'RedHat']
    - fpm_method_install == 'user'
    - ansible_virtualization_type == 'docker'
  become: yes
  block:
    - file:
        path: /etc/gemrc
        state: touch
    - lineinfile:
          path: /etc/gemrc
          line: "{{ item }}"
          state: present
      with_items:
        - '# https://stackoverflow.com/a/48212945/5430535'
        - 'gem: --user-install'
